  const { Model, DataTypes } = require('sequelize');
  module.exports=(sequelize)=>
  {
    class  CustomerMaster extends Model{}
    CustomerMaster.init(
        {
            CustomerID:
            {
                type:DataTypes.INTEGER,
                allowNull:false,
                primaryKey:true,
                autoIncrement:true,
            },
            CustomerName:
            {
                type:DataTypes.STRING,
                allowNull:false,
            },
            Email:
            {
                type:DataTypes.STRING,
            },
            PhoneNo:
            {
                type:DataTypes.STRING,
                allowNull:false,
            },
            Age:
            {
                type:DataTypes.INTEGER,
                allowNull:false,
            },
            Gender:
            {
                type:DataTypes.STRING,
                allowNull:false,
            },
            Address:
            {
                type:DataTypes.STRING,
                allowNull:false,
            },
            City:
            {
                type:DataTypes.STRING,
                allowNull:false,
            },
            State:
            {
                type:DataTypes.STRING,
                allowNull:false,
            },
            Pincode:
            {
                type:DataTypes.INTEGER,
                allowNull:false,
            },
            VehicleBrand:
            {
                type:DataTypes.STRING,
                allowNull:true,
            },
            VehicleModel:
            {
                type:DataTypes.STRING,
                allowNull:true,
            },
            PaymentMethod:
            {
                type:DataTypes.STRING,
            },
        },
        {
            sequelize,
            modelName:"CustomurMaster",
            tableName:"Automotive",
            timestamps:false,
        },
    );
    return CustomerMaster;
  };