const {Model,DataTypes}=require('sequelize');
module.exports=(sequelize)=>
{
    class Chef extends Model{};
    Chef.init(
        {
            ChefID:
            {
                type:DataTypes.INTEGER,
                primaryKey:true,
                allowNull:false,
                autoIncrement:true,
            },
            ChefName:
            {
                type:DataTypes.STRING,
                allowNull:false,
            },
            Email:
            {
                type:DataTypes.STRING,
                allowNull:false,
                unique:true,
            },
            Password:
            {
                type:DataTypes.STRING,
                allowNull:false,
            },
            Speciality:
            {
                type:DataTypes.STRING,
            },
            Reset_Token:
            {
                type:DataTypes.STRING,
            },
            Reset_Token_Expiry:
            {
                type:DataTypes.DATE,
            },
        },
        {
            sequelize,
            modelName:"Chef",
            tableName:"Chef",
            timestamps:false,
        },
    );
    return Chef;
};